<div align = "center">
Міністерство освіти і науки України<br>
Національний технічний університет України<br>  
"Київський політехнічний інститут ім. Ігоря Сікорського"<br>  
Теплоенергетичний факультет<br>
Кафедра автоматизації проектування енергетичних процесів та систем<br><br><br><br><br><br>       
Лабораторна робота №20<br>
з курсу<br>
"Основи програмування на скриптових мовах"<br><br>
Варіант №18
</div><br><br><br><br><br><br><br><br>
<div align = "right">
Виконав:<br>
Студент 2-го курсу<br>  
ТЕФ<br>
групи ТІ-81<br>  
Цимбалюк Д.В.<br><br> 
Перевірив:<br>  
Сігайов А.О.</div>
<div align ="center"><br><br><br>  
Київ КПІ 2019
</div>

## Варіант 18
<br>

**Умова завдання:**

**Завдання 392**

Дана квадратна матриця цілих чисел порядку 8. Знайти найменше зі значень елементів стовпця, який володіє найбільшою сумою елементів по модулю. Якщо таких стовпців кілька, то взяти перший з них.

In [6]:
from random import randint
import numpy as np

lst = np.array([[randint(-50, 50) for i in range(8)] for j in range(8)])
print(lst)
abs_sum = [sum([abs(elem[i]) for elem in lst]) for i in range(8)]
print('Min value: ', min([elem[abs_sum.index(max(abs_sum))] for elem in lst]))



[[-34 -33  41  -8  49  37  23 -20]
 [ 14  29  37  18  -3 -27 -29 -27]
 [ 22  40  22 -16  34  43 -34  39]
 [ 31  24 -40 -20   3   7 -16   9]
 [ -6  10 -30  23  20  16 -38 -40]
 [-11  -3 -40  50 -13  -8 -28  13]
 [-49  42 -50  38   1  -1  19  22]
 [ 38 -10  22  32 -45 -46   9   7]]
Min value:  -50
