<div align = "center">
Міністерство освіти і науки України<br>
Національний технічний університет України<br>  
"Київський політехнічний інститут ім. Ігоря Сікорського"<br>  
Теплоенергетичний факультет<br>
Кафедра автоматизації проектування енергетичних процесів та систем<br><br><br><br><br><br>       
Лабораторна робота №30<br>
з курсу<br>
"Основи програмування на скриптових мовах"<br><br>
Варіант №18
</div><br><br><br><br><br><br><br><br>
<div align = "right">
Виконав:<br>
Студент 2-го курсу<br>  
ТЕФ<br>
групи ТІ-81<br>  
Цимбалюк Д.В.<br><br> 
Перевірив:<br>  
Сігайов А.О.</div>
<div align ="center"><br><br><br>  
Київ КПІ 2019
</div>

## Варіант 18
<br>

**Умова завдання:**

**Завдання 676.**
Дана матриця цілих чисел розміром 6x9. Знайти матрицю, яка утворюється з даної: 

а) перестановкою стовпчиків - першого з останнім, другого з передостаннім і т. д; 

б) перестановкою рядків - першого до останнім, другого - з передостаннім і т. д.


In [6]:
from random import  randint
import numpy as np 
M = np.array([[randint(-10, 10) for i in range(9)] for j in range(6)])
print(M, '\n')
A = np.flip(M, 1)
print('A: \n')
print(A)
B = np.flip(M, 0)
print('B: \n')
print(B)

[[ -8  -5   3  10  -4   3   5  -9 -10]
 [ -9   0  -6   9  -4  -2   6   1  -8]
 [  4  -1   3   8  -2 -10 -10  -9   7]
 [ -4   8  -4  -6   5  -2  -2  -1  -5]
 [ -7  -7   4   5   2 -10   4   5   9]
 [  6  -8   6   0   3   6   9   5   4]] 

A: 

[[-10  -9   5   3  -4  10   3  -5  -8]
 [ -8   1   6  -2  -4   9  -6   0  -9]
 [  7  -9 -10 -10  -2   8   3  -1   4]
 [ -5  -1  -2  -2   5  -6  -4   8  -4]
 [  9   5   4 -10   2   5   4  -7  -7]
 [  4   5   9   6   3   0   6  -8   6]]
B: 

[[  6  -8   6   0   3   6   9   5   4]
 [ -7  -7   4   5   2 -10   4   5   9]
 [ -4   8  -4  -6   5  -2  -2  -1  -5]
 [  4  -1   3   8  -2 -10 -10  -9   7]
 [ -9   0  -6   9  -4  -2   6   1  -8]
 [ -8  -5   3  10  -4   3   5  -9 -10]]


**Умова завдання:**

**Завдання 714.**


Комплексна матриця $Z$ представляється парою $X$, $Y$ дійсних матриць так, що $Z = X - iY$. Дано дійсні квадратні матриці
 $A$, $В$, $С$ і $D$ порядку $n$. Знайти добуток двох комплексних матриць $A + iB$ і $C + iD$, тобто знайти дійсні
  квадратні матриці $X$ і $Y$ порядку n такі, що $X + iY = (A + iB) (С + iD)$.


In [41]:
import numpy as np
from random import randint

def main():
    n = int(input('Enter n: '))
    a = np.array([[randint(-30, 30) for i in range(n)] for j in range(n)])
    b = np.array([[randint(-30, 30) for i in range(n)] for j in range(n)])
    c = np.array([[randint(-30, 30) for i in range(n)] for j in range(n)])
    d = np.array([[randint(-30, 30) for i in range(n)] for j in range(n)])
    print(a, '\n\n', b, '\n\n', c, '\n\n', d, '\n\n')
    AB = np.array([[complex(a[i][j], b[i][j]) for j in range(n)] for i in range(n)])
    CD = np.array([[complex(c[i][j], d[i][j]) for j in range(n)] for i in range(n)])
    XY = np.dot(AB, CD)
    print(XY)
    x = np.array([[ XY[j][i].real for i in range(n)] for j in range(n)])
    y = np.array([[ XY[j][i].imag for i in range(n)] for j in range(n)])
    print('X:\n', x)
    print('Y:\n', y)

if __name__ == '__main__':
    try:
        main()
    except ValueError:
        print('n should be positive integer')

[[ -6 -18   0  -1  12]
 [ 15  16 -27  22   1]
 [ 12 -16 -26  16   1]
 [ -2   5  24 -22  13]
 [ -2  -1  30   5  -9]] 

 [[ -1   5  26   2   3]
 [-23  24  30  -3   4]
 [ 28 -29  28  11   4]
 [-16 -22 -21  18 -20]
 [  1  30 -27 -23  24]] 

 [[ 24  27  24 -21  13]
 [-24  11   9  -2  14]
 [  1   0  -8  23   3]
 [ 20  -3  22   3 -16]
 [-17 -20  19  30  -7]] 

 [[ 29   8  28 -24  16]
 [ -9  21  13 -11   4]
 [ 29  24 -11   0  26]
 [ -1  29 -24  11 -23]
 [-18   7   3  19 -18]] 


[[ -560. -356.j -1397. -409.j   188. -428.j   471.+1264.j  -978. -279.j]
 [  454.-1758.j  -486.  +25.j  1801. -166.j -1203. +961.j  -526. -775.j]
 [ -853.+1252.j  -554.  -69.j   876. +538.j  -584. +350.j -1144.-1096.j]
 [ -272.+1204.j   519. -210.j   563.  -86.j   464. -651.j  1321. +157.j]
 [ 1692. -613.j   609. +711.j -1697.  -86.j   630. -108.j   502.+1343.j]]
X:
 [[ -560. -1397.   188.   471.  -978.]
 [  454.  -486.  1801. -1203.  -526.]
 [ -853.  -554.   876.  -584. -1144.]
 [ -272.   519.   563.   464.  1321.]
 [